name: mc-installer
title: Minecraft Installer
adopt-info: launcher
summary: A simple installer for Minecraft - Java Edition
description: | 
  A simple installer for Minecraft - Java Edition.
license: MIT
website: https://minecraft.net
contact: https://github.com/kz6fittycent/mc-installer/issues
issues: https://github.com/kz6fittycent/mc-installer/issues
source-code: https://github.com/kz6fittycent/mc-installer
icon: snap/gui/mcinstaller.png
assumes:
  - command-chain
  
base: core24
grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
    
plugs:
  dot-minecraft:
    interface: personal-files
    write:
      - $HOME/.minecraft
apps:
  mc-installer:
    extensions:
      - gnome
    command: launch
    command-chain: 
      - bin/homeishome-launch    
    plugs:
      - network
      - opengl
      - audio-playback
      - browser-support
      - home
      - dot-minecraft   
      - removable-media
    environment:
      PYTHONPATH: $SNAP_DESKTOP_RUNTIME/usr/lib/python3.8/site-packages
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-amd64/
      __NV_PRIME_RENDER_OFFLOAD: 1
      __GLX_VENDOR_LIBRARY_NAME: nvidia      
parts:
  launcher:
    plugin: dump
    source: scripts
    
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
      
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch  
        
  game:
    plugin: nil
    build-packages:
      - openjdk-21-jre-headless        
      - ca-certificates-java
      - ca-certificates      
    stage-packages:
      - libglu1-mesa
      - libswt-gtk-4-java
      - python3-requests
      - openjdk-21-jre-headless
      - libxss1
      - libgconf-2-4
      - libcurl4
      - x11-xserver-utils
      - libflite1
      - python3-gi
     
  cleanup:
    after: 
      - game
      - launcher
    plugin: nil
    build-snaps: 
      - core22
      - gnome-42-2204
    override-prime: |
      set -eux
      for snap in "core24" "gnome-42-2204"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$CRAFT_PRIME/{}" \;
      done
